server:
  #eureka服务器端口号。尽管无论官网还是大部分参考书都使用8761，但默认并不是，而是8080
  port: 800
  
spring:
  application:
    name: happy-consumer

eureka:
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
      #Eureka服务器集群
      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址

ribbon:
  eureka:
    enabled: true

info:
  app.name: tj-happy
  company.name: www.tj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

